-- 제약조건

-- 1. NOT NULL
CREATE TABLE TBL_NN (
    LOGIN_ID  VARCHAR2(20) NOT NULL,
    LOGIN_PWD VARCHAR2(20) NOT NULL,
    TEL		  VARCHAR2(20)
);

SELECT * FROM tBL_NN;

INSERT INTO TBL_NN (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('hugo95', '12345', null);

INSERT INTO TBL_NN (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('ashely', NULL , '00-9999-6666');

INSERT INTO TBL_NN (LOGIN_ID, LOGIN_PWD)
VALUES ('hugo95', '12345');

INSERT INTO TBL_NN (lOGIN_PWD, tel)
VALUES ('9999', '010-0000-0000');

UPDATE tbl_nn SET
  login_pwd = NULL
WHERE login_id = 'hugo95';