SELECT *
  FROM emp
 WHERE ename LIKE '%S';

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP e 
 WHERE DEPTNO = 30
   AND JOB = 'SALESMAN';

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP 
 WHERE DEPTNO = 20 AND SAL > 2000
 UNION 
 SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP 
 WHERE DEPTNO = 30 AND SAL > 2000;

-- 5-3 (정답)
-- 집합연산자를 사용하지 않은 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO IN (20, 30) 
   AND SAL > 2000;

-- 집합연산자를 사용한 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20
   AND SAL > 2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND SAL > 2000;

--- 

SELECT *
  FROM EMP e
 WHERE SAL >= 2000 AND SAL <= 3000;

SELECT ENAME, EMPNO, SAL, DEPTNO
  FROM EMP e 
 WHERE ENAME LIKE '%E%'
   AND e.DEPTNO = 30;
   AND NOT sal >= 1000 AND NOT sal <= 2000;

-- 6번
SELECT *
  FROM EMP e 
 WHERE comm = NULL
   AND job IN (MANAGER, CLERK)
   AND NOT LIKE ENAME = '_L%';

-- 6번 정답
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND JOB IN ('MANAGER', 'CLERK')
   AND ENAME NOT LIKE '_L%';

---------------------


