-- sum 합산 함수
SELECT sum(SALARY)
  FROM EMPLOYEE;

-- 아무 의미 없음
SELECT SUM(*)
  FROM EPLOYEE;

-- 각 레코드 (행에 대한 한 줄을 의미함. - 한줄, 로우, 행)로 개수를 구할 수 있음.
SELECT COUNT(*)
  FROM EMPLOYEE;

-- 특정 컬럼의 갯수로 구할 수 있음
SELECT COUNT(EMP_NAME)
  FROM EMPLOYEE;

SELECT COUNT(DEPT_ID)
  FROM EMPLOYEE;

SELECT COUNT(DISTINCT DEPT_ID)
  FROM EMPLOYEE;

-- SALARY 합산 596, 490
-- SALARY 개수 97
-- 전체 데이터 100
SELECT AVG(SALARY)
  FROM EMPLOYEE;

SELECT MIN(SALARY), MAX(SALARY)
  FROM EMPLOYEE;

-- MIN, MAX는 날짜도 가능
SELECT MIN(HIRE_DATE), MAX(HIRE_DATE)
  FROM EMPLOYEE;