CREATE TABLE DIVTBL (
    DIVISION   CHAR(4)         CONSTRAINT PK_DIVTBL PRIMARY KEY,
    NAMES      VARCHAR2(45)    CONSTRAINT NN_DIVTBL_NAMES NOT NULL
);

CREATE TABLE BOOKSTBL (
    IDX           NUMBER(38,0)     CONSTRAINT PK_BOOKSTBL PRIMARY KEY,
    AUTHOR        VARCHAR2(45)     CONSTRAINT NN_BOOKSTBL_AUTHOR NOT NULL,
    DIVISION      CHAR(4)          CONSTRAINT FK_BOOKSTBL_DIVISION REFERENCES DIVTBL (DIVISION),
    NAMES         VARCHAR2(100)    CONSTRAINT NN_BOOKSTBL_NAMES NOT NULL,
    RELEASEDATE   DATE,
    ISBN          VARCHAR2(200)    CONSTRAINT UQ_BOOKSTBL_ISBN UNIQUE,
    PRICE         NUMBER(38,0)     CONSTRAINT CK_BOOKSTBL_PRICE CHECK (PRICE >= 0)
);

CREATE TABLE MEMBERTBL (
    IDX       NUMBER(38,0)     CONSTRAINT PK_MEMBERTBL PRIMARY KEY,
    NAMES     VARCHAR2(45)     CONSTRAINT NN_MEMBERTBL_NAMES NOT NULL,
    LEVELS    CHAR(1)          CONSTRAINT CK_MEMBERTBL_LEVELS CHECK (LEVELS IN ('A', 'B', 'C', 'D')),
    ADDR      VARCHAR2(100),
    MOBILE    VARCHAR2(13),
    EMAIL     VARCHAR2(50)     CONSTRAINT UQ_MEMBERTBL_EMAIL UNIQUE
);

CREATE TABLE RENTALTBL (
    IDX          NUMBER CONSTRAINT PK_RENTALTBL PRIMARY KEY,
    MEMBERIDX    NUMBER CONSTRAINT NN_RENTALTBL_MEMBERIDX NOT NULL,
    BOOKIDX      NUMBER CONSTRAINT NN_RENTALTBL_BOOKIDX NOT NULL,
    RENTALDATE   DATE   CONSTRAINT NN_RENTALTBL_RENTALDATE NOT NULL,
    RETURNDATE   DATE);

ALTER TABLE RENTALTBL ADD CONSTRAINT FK_RENTALTBL_MEMBERIDX
        FOREIGN KEY (MEMBERIDX)
        REFERENCES MEMBERTBL(IDX);

ALTER TABLE RENTALTBL ADD CONSTRAINT FK_RENTALTBL_BOOKIDX
        FOREIGN KEY (BOOKIDX)
        REFERENCES BOOKSTBL(IDX);