CREATE USER bookrentalshop
IDENTIFIED BY java12345
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CREATE SESSION TO bookrentalshop;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO bookrentalshop;

ALTER USER bookrentalshop QUOTA UNLIMITED ON users;