-- 시퀀스 생성
CREATE SEQUENCE seq_department START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_employee    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_customer    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_product     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_orders      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_order_item  START WITH 1 INCREMENT BY 1 NOCACHE;