-- DML 계속
SELECT *
  FROM EMP_TEMP;

-- INSET
INSERT INTO EMP_TEMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9999, '홍길동', 'PRESIDENT', NULL, '2001-01-01', 5000, 1000, 10);

-- 날짜 포맷이 다르면 날짜함수로 변경해주면 된다.


-- 
SELECT *
  FROM EMP E, SALGRADE S
 WHERE E.SAL BETWEEN S.LASAL AND S.HISAL
   AND S.GRDE =1;