-- DML - UPDATE

-- DEPT_TEMP2 생성
CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;

-- 확인 조회
SELECT * FROM DEPT_TEMP2;

-- 전체데이터 수정! (조심)
UPDATE DEPT_TEMP2
   SET LOC = 'SEOUL';

-- DELETE FROM DEPT_TEMP2;

INSERT INTO DEPT_TEMP2 (DEPTNO, DNAME, LOC)
SELECT DEPTNO, DNAME, LOC -- 1. 먼저 적어주기
  FROM DEPT;

-- 일반적인 UPDATE
UPDATE DEPT_TEMP2
   SET LOC = 'BUSAN'
 WHERE DEPTNO = 40;

-- 서브쿼리로 업데이트
UPDATE DEPT_TEMP2
   SET LOC = 'LOS ANGELUS'
 WHERE DEPTNO = (SELECT DEPTNO
			       FROM DEPT_TEMP2
				  WHERE DNAME = 'OPERATIONS');

SELECT * FROM DEPT_TEMP2;

-- DML - DELETE
SELECT * FROM EMP_TEMP;

-- JOB이 CLERK(사무원)인 데이터 삭제
-- 1. SELECT문으로 WHERE절로 조회하고
SELECT * FROM EMP_TEMP
 WHERE JOB = 'CLERK';

-- 10 SELECT *을 DELETE로 변경, 실행
DELETE FROM EMP_TEMP
  WHERE JOB = 'CLERK';
